name: Deploy Docs

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clean install
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Build docs
        run: npm run build

      - name: Deploy to Firebase
        uses: docker://w9jds/firebase-action:master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
